// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsSnmp) DeepCopyInto(out *AnalyticsSnmp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsSnmp.
func (in *AnalyticsSnmp) DeepCopy() *AnalyticsSnmp {
	if in == nil {
		return nil
	}
	out := new(AnalyticsSnmp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsSnmp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsSnmpConfiguration) DeepCopyInto(out *AnalyticsSnmpConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.SnmpCollectorScanFrequency != nil {
		in, out := &in.SnmpCollectorScanFrequency, &out.SnmpCollectorScanFrequency
		*out = new(int)
		**out = **in
	}
	if in.SnmpCollectorFastScanFrequency != nil {
		in, out := &in.SnmpCollectorFastScanFrequency, &out.SnmpCollectorFastScanFrequency
		*out = new(int)
		**out = **in
	}
	if in.SnmpCollectorIntrospectListenPort != nil {
		in, out := &in.SnmpCollectorIntrospectListenPort, &out.SnmpCollectorIntrospectListenPort
		*out = new(int)
		**out = **in
	}
	if in.TopologyScanFrequency != nil {
		in, out := &in.TopologyScanFrequency, &out.TopologyScanFrequency
		*out = new(int)
		**out = **in
	}
	if in.TopologyIntrospectListenPort != nil {
		in, out := &in.TopologyIntrospectListenPort, &out.TopologyIntrospectListenPort
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsSnmpConfiguration.
func (in *AnalyticsSnmpConfiguration) DeepCopy() *AnalyticsSnmpConfiguration {
	if in == nil {
		return nil
	}
	out := new(AnalyticsSnmpConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsSnmpSpec) DeepCopyInto(out *AnalyticsSnmpSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsSnmpSpec.
func (in *AnalyticsSnmpSpec) DeepCopy() *AnalyticsSnmpSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyticsSnmpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsSnmpStatus) DeepCopyInto(out *AnalyticsSnmpStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.ConfigChanged != nil {
		in, out := &in.ConfigChanged, &out.ConfigChanged
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsSnmpStatus.
func (in *AnalyticsSnmpStatus) DeepCopy() *AnalyticsSnmpStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyticsSnmpStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsSnmpList) DeepCopyInto(out *AnalyticsSnmpList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnalyticsSnmp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlList.
func (in *AnalyticsSnmpList) DeepCopy() *AnalyticsSnmpList {
	if in == nil {
		return nil
	}
	out := new(AnalyticsSnmpList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsSnmpList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsAlarm) DeepCopyInto(out *AnalyticsAlarm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsAlarm.
func (in *AnalyticsAlarm) DeepCopy() *AnalyticsAlarm {
	if in == nil {
		return nil
	}
	out := new(AnalyticsAlarm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsAlarm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsAlarmConfiguration) DeepCopyInto(out *AnalyticsAlarmConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AlarmgenRedisAggregateDbOffset != nil {
		in, out := &in.AlarmgenRedisAggregateDbOffset, &out.AlarmgenRedisAggregateDbOffset
		*out = new(int)
		**out = **in
	}
	if in.AlarmgenPartitions != nil {
		in, out := &in.AlarmgenPartitions, &out.AlarmgenPartitions
		*out = new(int)
		**out = **in
	}
	if in.AlarmgenIntrospectListenPort != nil {
		in, out := &in.AlarmgenIntrospectListenPort, &out.AlarmgenIntrospectListenPort
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsAlarmConfiguration.
func (in *AnalyticsAlarmConfiguration) DeepCopy() *AnalyticsAlarmConfiguration {
	if in == nil {
		return nil
	}
	out := new(AnalyticsAlarmConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsAlarmSpec) DeepCopyInto(out *AnalyticsAlarmSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsAlarmSpec.
func (in *AnalyticsAlarmSpec) DeepCopy() *AnalyticsAlarmSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyticsAlarmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsAlarmStatus) DeepCopyInto(out *AnalyticsAlarmStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.ConfigChanged != nil {
		in, out := &in.ConfigChanged, &out.ConfigChanged
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyticsAlarmStatus.
func (in *AnalyticsAlarmStatus) DeepCopy() *AnalyticsAlarmStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyticsAlarmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyticsAlarmList) DeepCopyInto(out *AnalyticsAlarmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnalyticsAlarm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlList.
func (in *AnalyticsAlarmList) DeepCopy() *AnalyticsAlarmList {
	if in == nil {
		return nil
	}
	out := new(AnalyticsAlarmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyticsAlarmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPPeer) DeepCopyInto(out *BGPPeer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPPeer.
func (in *BGPPeer) DeepCopy() *BGPPeer {
	if in == nil {
		return nil
	}
	out := new(BGPPeer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cassandra) DeepCopyInto(out *Cassandra) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cassandra.
func (in *Cassandra) DeepCopy() *Cassandra {
	if in == nil {
		return nil
	}
	out := new(Cassandra)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cassandra) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraClusterConfiguration) DeepCopyInto(out *CassandraClusterConfiguration) {
	*out = *in
	if in.ServerIPList != nil {
		in, out := &in.ServerIPList, &out.ServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraClusterConfiguration.
func (in *CassandraClusterConfiguration) DeepCopy() *CassandraClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(CassandraClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraConfiguration) DeepCopyInto(out *CassandraConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.CqlPort != nil {
		in, out := &in.CqlPort, &out.CqlPort
		*out = new(int)
		**out = **in
	}
	if in.SslStoragePort != nil {
		in, out := &in.SslStoragePort, &out.SslStoragePort
		*out = new(int)
		**out = **in
	}
	if in.StoragePort != nil {
		in, out := &in.StoragePort, &out.StoragePort
		*out = new(int)
		**out = **in
	}
	if in.JmxLocalPort != nil {
		in, out := &in.JmxLocalPort, &out.JmxLocalPort
		*out = new(int)
		**out = **in
	}
	if in.StartRPC != nil {
		in, out := &in.StartRPC, &out.StartRPC
		*out = new(bool)
		**out = **in
	}
	if in.MinimumDiskGB != nil {
		in, out := &in.MinimumDiskGB, &out.MinimumDiskGB
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraConfiguration.
func (in *CassandraConfiguration) DeepCopy() *CassandraConfiguration {
	if in == nil {
		return nil
	}
	out := new(CassandraConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraList) DeepCopyInto(out *CassandraList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cassandra, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraList.
func (in *CassandraList) DeepCopy() *CassandraList {
	if in == nil {
		return nil
	}
	out := new(CassandraList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CassandraList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraSpec) DeepCopyInto(out *CassandraSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraSpec.
func (in *CassandraSpec) DeepCopy() *CassandraSpec {
	if in == nil {
		return nil
	}
	out := new(CassandraSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraStatus) DeepCopyInto(out *CassandraStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.ConfigChanged != nil {
		in, out := &in.ConfigChanged, &out.ConfigChanged
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Ports = in.Ports
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraStatus.
func (in *CassandraStatus) DeepCopy() *CassandraStatus {
	if in == nil {
		return nil
	}
	out := new(CassandraStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CassandraStatusPorts) DeepCopyInto(out *CassandraStatusPorts) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CassandraStatusPorts.
func (in *CassandraStatusPorts) DeepCopy() *CassandraStatusPorts {
	if in == nil {
		return nil
	}
	out := new(CassandraStatusPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Config) DeepCopyInto(out *Config) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Config.
func (in *Config) DeepCopy() *Config {
	if in == nil {
		return nil
	}
	out := new(Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Config) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthParameters) DeepCopyInto(out *AuthParameters) {
	*out = *in
	if in.KeystoneAuthParameters != nil {
		in, out := &in.KeystoneAuthParameters, &out.KeystoneAuthParameters
		*out = new(KeystoneAuthParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.KeystoneSecretName != nil {
		in, out := &in.KeystoneSecretName, &out.KeystoneSecretName
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeystoneAuthParameters) DeepCopyInto(out *KeystoneAuthParameters) {
	*out = *in
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.AdminPort != nil {
		in, out := &in.AdminPort, &out.AdminPort
		*out = new(int)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.AdminPassword != nil {
		in, out := &in.AdminPassword, &out.AdminPassword
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthParameters.
func (in *AuthParameters) DeepCopy() *AuthParameters {
	if in == nil {
		return nil
	}
	out := new(AuthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigClusterConfiguration) DeepCopyInto(out *ConfigClusterConfiguration) {
	*out = *in
	if in.APIServerIPList != nil {
		in, out := &in.APIServerIPList, &out.APIServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AnalyticsServerIPList != nil {
		in, out := &in.AnalyticsServerIPList, &out.AnalyticsServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CollectorServerIPList != nil {
		in, out := &in.CollectorServerIPList, &out.CollectorServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigClusterConfiguration.
func (in *ConfigClusterConfiguration) DeepCopy() *ConfigClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ConfigClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigConfiguration) DeepCopyInto(out *ConfigConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.APIPort != nil {
		in, out := &in.APIPort, &out.APIPort
		*out = new(int)
		**out = **in
	}
	if in.AnalyticsPort != nil {
		in, out := &in.AnalyticsPort, &out.AnalyticsPort
		*out = new(int)
		**out = **in
	}
	if in.CollectorPort != nil {
		in, out := &in.CollectorPort, &out.CollectorPort
		*out = new(int)
		**out = **in
	}
	if in.ApiIntrospectPort != nil {
		in, out := &in.ApiIntrospectPort, &out.ApiIntrospectPort
		*out = new(int)
		**out = **in
	}
	if in.SchemaIntrospectPort != nil {
		in, out := &in.SchemaIntrospectPort, &out.SchemaIntrospectPort
		*out = new(int)
		**out = **in
	}
	if in.DeviceManagerIntrospectPort != nil {
		in, out := &in.DeviceManagerIntrospectPort, &out.DeviceManagerIntrospectPort
		*out = new(int)
		**out = **in
	}
	if in.SvcMonitorIntrospectPort != nil {
		in, out := &in.SvcMonitorIntrospectPort, &out.SvcMonitorIntrospectPort
		*out = new(int)
		**out = **in
	}
	if in.AnalyticsApiIntrospectPort != nil {
		in, out := &in.AnalyticsApiIntrospectPort, &out.AnalyticsApiIntrospectPort
		*out = new(int)
		**out = **in
	}
	if in.CollectorIntrospectPort != nil {
		in, out := &in.CollectorIntrospectPort, &out.CollectorIntrospectPort
		*out = new(int)
		**out = **in
	}
	if in.AnalyticsDataTTL != nil {
		in, out := &in.AnalyticsDataTTL, &out.AnalyticsDataTTL
		*out = new(int)
		**out = **in
	}
	if in.AnalyticsConfigAuditTTL != nil {
		in, out := &in.AnalyticsConfigAuditTTL, &out.AnalyticsConfigAuditTTL
		*out = new(int)
		**out = **in
	}
	if in.AnalyticsStatisticsTTL != nil {
		in, out := &in.AnalyticsStatisticsTTL, &out.AnalyticsStatisticsTTL
		*out = new(int)
		**out = **in
	}
	if in.AnalyticsFlowTTL != nil {
		in, out := &in.AnalyticsFlowTTL, &out.AnalyticsFlowTTL
		*out = new(int)
		**out = **in
	}
	if in.LinklocalServiceConfig != nil {
		in, out := &in.LinklocalServiceConfig, &out.LinklocalServiceConfig
		*out = new(LinklocalServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.UseExternalTFTP != nil {
		in, out := &in.UseExternalTFTP, &out.UseExternalTFTP
		*out = new(bool)
		**out = **in
	}
	if in.BgpAutoMesh != nil {
		in, out := &in.BgpAutoMesh, &out.BgpAutoMesh
		*out = new(bool)
		**out = **in
	}
	if in.BgpEnable4Byte != nil {
		in, out := &in.BgpEnable4Byte, &out.BgpEnable4Byte
		*out = new(bool)
		**out = **in
	}
	if in.GloblaASNNumber != nil {
		in, out := &in.GloblaASNNumber, &out.GloblaASNNumber
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinklocalServiceConfig) DeepCopyInto(out *LinklocalServiceConfig) {
	*out = *in
	if in.IPFabricServicePort != nil {
		in, out := &in.IPFabricServicePort, &out.IPFabricServicePort
		*out = new(int)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigConfiguration.
func (in *ConfigConfiguration) DeepCopy() *ConfigConfiguration {
	if in == nil {
		return nil
	}
	out := new(ConfigConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigList) DeepCopyInto(out *ConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Config, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigList.
func (in *ConfigList) DeepCopy() *ConfigList {
	if in == nil {
		return nil
	}
	out := new(ConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSpec) DeepCopyInto(out *ConfigSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSpec.
func (in *ConfigSpec) DeepCopy() *ConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStatus) DeepCopyInto(out *ConfigStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigChanged != nil {
		in, out := &in.ConfigChanged, &out.ConfigChanged
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStatus.
func (in *ConfigStatus) DeepCopy() *ConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Connection) DeepCopyInto(out *Connection) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Connection.
func (in *Connection) DeepCopy() *Connection {
	if in == nil {
		return nil
	}
	out := new(Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Container) DeepCopyInto(out *Container) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Container.
func (in *Container) DeepCopy() *Container {
	if in == nil {
		return nil
	}
	out := new(Container)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Control) DeepCopyInto(out *Control) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Control.
func (in *Control) DeepCopy() *Control {
	if in == nil {
		return nil
	}
	out := new(Control)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Control) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlClusterConfiguration) DeepCopyInto(out *ControlClusterConfiguration) {
	*out = *in
	if in.ControlServerIPList != nil {
		in, out := &in.ControlServerIPList, &out.ControlServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlClusterConfiguration.
func (in *ControlClusterConfiguration) DeepCopy() *ControlClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControlClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlConfiguration) DeepCopyInto(out *ControlConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.BGPPort != nil {
		in, out := &in.BGPPort, &out.BGPPort
		*out = new(int)
		**out = **in
	}
	if in.ASNNumber != nil {
		in, out := &in.ASNNumber, &out.ASNNumber
		*out = new(int)
		**out = **in
	}
	if in.XMPPPort != nil {
		in, out := &in.XMPPPort, &out.XMPPPort
		*out = new(int)
		**out = **in
	}
	if in.DNSPort != nil {
		in, out := &in.DNSPort, &out.DNSPort
		*out = new(int)
		**out = **in
	}
	if in.DNSIntrospectPort != nil {
		in, out := &in.DNSIntrospectPort, &out.DNSIntrospectPort
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlConfiguration.
func (in *ControlConfiguration) DeepCopy() *ControlConfiguration {
	if in == nil {
		return nil
	}
	out := new(ControlConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlList) DeepCopyInto(out *ControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Control, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlList.
func (in *ControlList) DeepCopy() *ControlList {
	if in == nil {
		return nil
	}
	out := new(ControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlServiceStatus) DeepCopyInto(out *ControlServiceStatus) {
	*out = *in
	if in.Connections != nil {
		in, out := &in.Connections, &out.Connections
		*out = make([]Connection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.StaticRoutes = in.StaticRoutes
	out.BGPPeer = in.BGPPeer
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlServiceStatus.
func (in *ControlServiceStatus) DeepCopy() *ControlServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ControlServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlSpec) DeepCopyInto(out *ControlSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlSpec.
func (in *ControlSpec) DeepCopy() *ControlSpec {
	if in == nil {
		return nil
	}
	out := new(ControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlStatus) DeepCopyInto(out *ControlStatus) {
	*out = *in
	if in.ConfigChanged != nil {
		in, out := &in.ConfigChanged, &out.ConfigChanged
		*out = new(bool)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Ports = in.Ports
	if in.ServiceStatus != nil {
		in, out := &in.ServiceStatus, &out.ServiceStatus
		*out = make(map[string]ControlServiceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlStatus.
func (in *ControlStatus) DeepCopy() *ControlStatus {
	if in == nil {
		return nil
	}
	out := new(ControlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ControlStatusPorts) DeepCopyInto(out *ControlStatusPorts) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ControlStatusPorts.
func (in *ControlStatusPorts) DeepCopy() *ControlStatusPorts {
	if in == nil {
		return nil
	}
	out := new(ControlStatusPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrdStatus) DeepCopyInto(out *CrdStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrdStatus.
func (in *CrdStatus) DeepCopy() *CrdStatus {
	if in == nil {
		return nil
	}
	out := new(CrdStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubemanager) DeepCopyInto(out *Kubemanager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubemanager.
func (in *Kubemanager) DeepCopy() *Kubemanager {
	if in == nil {
		return nil
	}
	out := new(Kubemanager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Kubemanager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerConfiguration) DeepCopyInto(out *KubemanagerConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.KubernetesAPIPort != nil {
		in, out := &in.KubernetesAPIPort, &out.KubernetesAPIPort
		*out = new(int)
		**out = **in
	}
	if in.KubernetesAPISSLPort != nil {
		in, out := &in.KubernetesAPISSLPort, &out.KubernetesAPISSLPort
		*out = new(int)
		**out = **in
	}
	if in.IPFabricForwarding != nil {
		in, out := &in.IPFabricForwarding, &out.IPFabricForwarding
		*out = new(bool)
		**out = **in
	}
	if in.IPFabricSnat != nil {
		in, out := &in.IPFabricSnat, &out.IPFabricSnat
		*out = new(bool)
		**out = **in
	}
	if in.HostNetworkService != nil {
		in, out := &in.HostNetworkService, &out.HostNetworkService
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerConfiguration.
func (in *KubemanagerConfiguration) DeepCopy() *KubemanagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubemanagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerList) DeepCopyInto(out *KubemanagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Kubemanager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerList.
func (in *KubemanagerList) DeepCopy() *KubemanagerList {
	if in == nil {
		return nil
	}
	out := new(KubemanagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KubemanagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerService) DeepCopyInto(out *KubemanagerService) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerService.
func (in *KubemanagerService) DeepCopy() *KubemanagerService {
	if in == nil {
		return nil
	}
	out := new(KubemanagerService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerServiceConfiguration) DeepCopyInto(out *KubemanagerServiceConfiguration) {
	*out = *in
	in.KubemanagerConfiguration.DeepCopyInto(&out.KubemanagerConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerServiceConfiguration.
func (in *KubemanagerServiceConfiguration) DeepCopy() *KubemanagerServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubemanagerServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerServiceSpec) DeepCopyInto(out *KubemanagerServiceSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerServiceSpec.
func (in *KubemanagerServiceSpec) DeepCopy() *KubemanagerServiceSpec {
	if in == nil {
		return nil
	}
	out := new(KubemanagerServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerSpec) DeepCopyInto(out *KubemanagerSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerSpec.
func (in *KubemanagerSpec) DeepCopy() *KubemanagerSpec {
	if in == nil {
		return nil
	}
	out := new(KubemanagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubemanagerStatus) DeepCopyInto(out *KubemanagerStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ConfigChanged != nil {
		in, out := &in.ConfigChanged, &out.ConfigChanged
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubemanagerStatus.
func (in *KubemanagerStatus) DeepCopy() *KubemanagerStatus {
	if in == nil {
		return nil
	}
	out := new(KubemanagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Manager) DeepCopyInto(out *Manager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Manager.
func (in *Manager) DeepCopy() *Manager {
	if in == nil {
		return nil
	}
	out := new(Manager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Manager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerCondition) DeepCopyInto(out *ManagerCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerCondition.
func (in *ManagerCondition) DeepCopy() *ManagerCondition {
	if in == nil {
		return nil
	}
	out := new(ManagerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfiguration) DeepCopyInto(out *ManagerConfiguration) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthParameters != nil {
		in, out := &in.AuthParameters, &out.AuthParameters
		*out = new(AuthParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.TuneSysctl != nil {
		in, out := &in.TuneSysctl, &out.TuneSysctl
		*out = new(bool)
		**out = **in
	}
	if in.ClusterConfig != nil {
		in, out := &in.ClusterConfig, &out.ClusterConfig
		*out = new(KubernetesClusterConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfiguration.
func (in *ManagerConfiguration) DeepCopy() *ManagerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ManagerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerList) DeepCopyInto(out *ManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Manager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerList.
func (in *ManagerList) DeepCopy() *ManagerList {
	if in == nil {
		return nil
	}
	out := new(ManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerSpec) DeepCopyInto(out *ManagerSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.Services.DeepCopyInto(&out.Services)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerSpec.
func (in *ManagerSpec) DeepCopy() *ManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerStatus) DeepCopyInto(out *ManagerStatus) {
	*out = *in
	if in.AnalyticsSnmp != nil {
		in, out := &in.AnalyticsSnmp, &out.AnalyticsSnmp
		*out = new(ServiceStatus)
		(*in).DeepCopyInto(*out)
	}

	if in.AnalyticsAlarm != nil {
		in, out := &in.AnalyticsAlarm, &out.AnalyticsAlarm
		*out = new(ServiceStatus)
		(*in).DeepCopyInto(*out)
	}

	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(ServiceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]*ServiceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Kubemanagers != nil {
		in, out := &in.Kubemanagers, &out.Kubemanagers
		*out = make([]*ServiceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Webui != nil {
		in, out := &in.Webui, &out.Webui
		*out = new(ServiceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Vrouters != nil {
		in, out := &in.Vrouters, &out.Vrouters
		*out = make([]*ServiceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Cassandras != nil {
		in, out := &in.Cassandras, &out.Cassandras
		*out = make([]*ServiceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Zookeepers != nil {
		in, out := &in.Zookeepers, &out.Zookeepers
		*out = make([]*ServiceStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ServiceStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Rabbitmq != nil {
		in, out := &in.Rabbitmq, &out.Rabbitmq
		*out = new(ServiceStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.CrdStatus != nil {
		in, out := &in.CrdStatus, &out.CrdStatus
		*out = make([]CrdStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ManagerCondition, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerStatus.
func (in *ManagerStatus) DeepCopy() *ManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConfiguration) DeepCopyInto(out *PodConfiguration) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostNetwork != nil {
		in, out := &in.HostNetwork, &out.HostNetwork
		*out = new(bool)
		**out = **in
	}
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]v1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.AuthParameters != nil {
		in, out := &in.AuthParameters, &out.AuthParameters
		*out = new(AuthParameters)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConfiguration.
func (in *PodConfiguration) DeepCopy() *PodConfiguration {
	if in == nil {
		return nil
	}
	out := new(PodConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Rabbitmq) DeepCopyInto(out *Rabbitmq) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Rabbitmq.
func (in *Rabbitmq) DeepCopy() *Rabbitmq {
	if in == nil {
		return nil
	}
	out := new(Rabbitmq)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Rabbitmq) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqClusterConfiguration) DeepCopyInto(out *RabbitmqClusterConfiguration) {
	*out = *in
	if in.ServerIPList != nil {
		in, out := &in.ServerIPList, &out.ServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqClusterConfiguration.
func (in *RabbitmqClusterConfiguration) DeepCopy() *RabbitmqClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(RabbitmqClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqConfiguration) DeepCopyInto(out *RabbitmqConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
	if in.ErlEpmdPort != nil {
		in, out := &in.ErlEpmdPort, &out.ErlEpmdPort
		*out = new(int)
		**out = **in
	}
	if in.MirroredQueueMode != nil {
		in, out := &in.MirroredQueueMode, &out.MirroredQueueMode
		*out = new(string)
		**out = **in
	}
	if in.ClusterPartitionHandling != nil {
		in, out := &in.ClusterPartitionHandling, &out.ClusterPartitionHandling
		*out = new(string)
		**out = **in
	}
	if in.TCPListenOptions != nil {
		in, out := &in.TCPListenOptions, &out.TCPListenOptions
		*out = new(TCPListenOptionsConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPListenOptionsConfig) DeepCopyInto(out *TCPListenOptionsConfig) {
	if in.Backlog != nil {
		in, out := &in.Backlog, &out.Backlog
		*out = new(int)
		**out = **in
	}
	if in.Nodelay != nil {
		in, out := &in.Nodelay, &out.Nodelay
		*out = new(bool)
		**out = **in
	}
	if in.LingerOn != nil {
		in, out := &in.LingerOn, &out.LingerOn
		*out = new(bool)
		**out = **in
	}
	if in.LingerTimeout != nil {
		in, out := &in.LingerTimeout, &out.LingerTimeout
		*out = new(int)
		**out = **in
	}
	if in.ExitOnClose != nil {
		in, out := &in.ExitOnClose, &out.ExitOnClose
		*out = new(bool)
		**out = **in
	}
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqList) DeepCopyInto(out *RabbitmqList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Rabbitmq, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqList.
func (in *RabbitmqList) DeepCopy() *RabbitmqList {
	if in == nil {
		return nil
	}
	out := new(RabbitmqList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RabbitmqList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqSpec) DeepCopyInto(out *RabbitmqSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqSpec.
func (in *RabbitmqSpec) DeepCopy() *RabbitmqSpec {
	if in == nil {
		return nil
	}
	out := new(RabbitmqSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitmqStatus) DeepCopyInto(out *RabbitmqStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitmqStatus.
func (in *RabbitmqStatus) DeepCopy() *RabbitmqStatus {
	if in == nil {
		return nil
	}
	out := new(RabbitmqStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Created != nil {
		in, out := &in.Created, &out.Created
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Services) DeepCopyInto(out *Services) {
	*out = *in
	if in.AnalyticsSnmp != nil {
		in, out := &in.AnalyticsSnmp, &out.AnalyticsSnmp
		*out = new(AnalyticsSnmp)
		(*in).DeepCopyInto(*out)
	}

	if in.AnalyticsAlarm != nil {
		in, out := &in.AnalyticsAlarm, &out.AnalyticsAlarm
		*out = new(AnalyticsAlarm)
		(*in).DeepCopyInto(*out)
	}

	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(Config)
		(*in).DeepCopyInto(*out)
	}
	if in.Controls != nil {
		in, out := &in.Controls, &out.Controls
		*out = make([]*Control, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Control)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Kubemanagers != nil {
		in, out := &in.Kubemanagers, &out.Kubemanagers
		*out = make([]*KubemanagerService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(KubemanagerService)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Webui != nil {
		in, out := &in.Webui, &out.Webui
		*out = new(Webui)
		(*in).DeepCopyInto(*out)
	}
	if in.Vrouters != nil {
		in, out := &in.Vrouters, &out.Vrouters
		*out = make([]*VrouterService, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(VrouterService)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Cassandras != nil {
		in, out := &in.Cassandras, &out.Cassandras
		*out = make([]*Cassandra, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Cassandra)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Zookeepers != nil {
		in, out := &in.Zookeepers, &out.Zookeepers
		*out = make([]*Zookeeper, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Zookeeper)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Rabbitmq != nil {
		in, out := &in.Rabbitmq, &out.Rabbitmq
		*out = new(Rabbitmq)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Services.
func (in *Services) DeepCopy() *Services {
	if in == nil {
		return nil
	}
	out := new(Services)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticRoutes) DeepCopyInto(out *StaticRoutes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticRoutes.
func (in *StaticRoutes) DeepCopy() *StaticRoutes {
	if in == nil {
		return nil
	}
	out := new(StaticRoutes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vrouter) DeepCopyInto(out *Vrouter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vrouter.
func (in *Vrouter) DeepCopy() *Vrouter {
	if in == nil {
		return nil
	}
	out := new(Vrouter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vrouter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterConfiguration) DeepCopyInto(out *VrouterConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = new(Distribution)
		**out = **in
	}
	if in.EnvVariablesConfig != nil {
		in, out := &in.EnvVariablesConfig, &out.EnvVariablesConfig
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CniMTU != nil {
		in, out := &in.CniMTU, &out.CniMTU
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterConfiguration.
func (in *VrouterConfiguration) DeepCopy() *VrouterConfiguration {
	if in == nil {
		return nil
	}
	out := new(VrouterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterList) DeepCopyInto(out *VrouterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vrouter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterList.
func (in *VrouterList) DeepCopy() *VrouterList {
	if in == nil {
		return nil
	}
	out := new(VrouterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VrouterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterManagerServiceConfiguration) DeepCopyInto(out *VrouterManagerServiceConfiguration) {
	*out = *in
	in.VrouterConfiguration.DeepCopyInto(&out.VrouterConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterManagerServiceConfiguration.
func (in *VrouterManagerServiceConfiguration) DeepCopy() *VrouterManagerServiceConfiguration {
	if in == nil {
		return nil
	}
	out := new(VrouterManagerServiceConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterNodesConfiguration) DeepCopyInto(out *VrouterNodesConfiguration) {
	*out = *in
	if in.ControlNodesConfiguration != nil {
		in, out := &in.ControlNodesConfiguration, &out.ControlNodesConfiguration
		*out = new(ControlClusterConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigNodesConfiguration != nil {
		in, out := &in.ConfigNodesConfiguration, &out.ConfigNodesConfiguration
		*out = new(ConfigClusterConfiguration)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterNodesConfiguration.
func (in *VrouterNodesConfiguration) DeepCopy() *VrouterNodesConfiguration {
	if in == nil {
		return nil
	}
	out := new(VrouterNodesConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterService) DeepCopyInto(out *VrouterService) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterService.
func (in *VrouterService) DeepCopy() *VrouterService {
	if in == nil {
		return nil
	}
	out := new(VrouterService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterServiceSpec) DeepCopyInto(out *VrouterServiceSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterServiceSpec.
func (in *VrouterServiceSpec) DeepCopy() *VrouterServiceSpec {
	if in == nil {
		return nil
	}
	out := new(VrouterServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterSpec) DeepCopyInto(out *VrouterSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterSpec.
func (in *VrouterSpec) DeepCopy() *VrouterSpec {
	if in == nil {
		return nil
	}
	out := new(VrouterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrouterStatus) DeepCopyInto(out *VrouterStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.ActiveOnControllers != nil {
		in, out := &in.ActiveOnControllers, &out.ActiveOnControllers
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrouterStatus.
func (in *VrouterStatus) DeepCopy() *VrouterStatus {
	if in == nil {
		return nil
	}
	out := new(VrouterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebUIServiceStatus) DeepCopyInto(out *WebUIServiceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebUIServiceStatus.
func (in *WebUIServiceStatus) DeepCopy() *WebUIServiceStatus {
	if in == nil {
		return nil
	}
	out := new(WebUIServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in WebUIServiceStatusMap) DeepCopyInto(out *WebUIServiceStatusMap) {
	{
		in := &in
		*out = make(WebUIServiceStatusMap, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebUIServiceStatusMap.
func (in WebUIServiceStatusMap) DeepCopy() WebUIServiceStatusMap {
	if in == nil {
		return nil
	}
	out := new(WebUIServiceStatusMap)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebUIStatusPorts) DeepCopyInto(out *WebUIStatusPorts) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebUIStatusPorts.
func (in *WebUIStatusPorts) DeepCopy() *WebUIStatusPorts {
	if in == nil {
		return nil
	}
	out := new(WebUIStatusPorts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Webui) DeepCopyInto(out *Webui) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Webui.
func (in *Webui) DeepCopy() *Webui {
	if in == nil {
		return nil
	}
	out := new(Webui)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Webui) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebuiConfiguration) DeepCopyInto(out *WebuiConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebuiConfiguration.
func (in *WebuiConfiguration) DeepCopy() *WebuiConfiguration {
	if in == nil {
		return nil
	}
	out := new(WebuiConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebuiList) DeepCopyInto(out *WebuiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Webui, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebuiList.
func (in *WebuiList) DeepCopy() *WebuiList {
	if in == nil {
		return nil
	}
	out := new(WebuiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebuiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebuiSpec) DeepCopyInto(out *WebuiSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebuiSpec.
func (in *WebuiSpec) DeepCopy() *WebuiSpec {
	if in == nil {
		return nil
	}
	out := new(WebuiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebuiStatus) DeepCopyInto(out *WebuiStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	out.Ports = in.Ports
	if in.ServiceStatus != nil {
		in, out := &in.ServiceStatus, &out.ServiceStatus
		*out = make(map[string]WebUIServiceStatusMap, len(*in))
		for key, val := range *in {
			var outVal map[string]WebUIServiceStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = make(WebUIServiceStatusMap, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebuiStatus.
func (in *WebuiStatus) DeepCopy() *WebuiStatus {
	if in == nil {
		return nil
	}
	out := new(WebuiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Zookeeper) DeepCopyInto(out *Zookeeper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Zookeeper.
func (in *Zookeeper) DeepCopy() *Zookeeper {
	if in == nil {
		return nil
	}
	out := new(Zookeeper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Zookeeper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperClusterConfiguration) DeepCopyInto(out *ZookeeperClusterConfiguration) {
	*out = *in
	if in.ServerIPList != nil {
		in, out := &in.ServerIPList, &out.ServerIPList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperClusterConfiguration.
func (in *ZookeeperClusterConfiguration) DeepCopy() *ZookeeperClusterConfiguration {
	if in == nil {
		return nil
	}
	out := new(ZookeeperClusterConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperConfiguration) DeepCopyInto(out *ZookeeperConfiguration) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]*Container, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Container)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.ClientPort != nil {
		in, out := &in.ClientPort, &out.ClientPort
		*out = new(int)
		**out = **in
	}
	if in.ElectionPort != nil {
		in, out := &in.ElectionPort, &out.ElectionPort
		*out = new(int)
		**out = **in
	}
	if in.ServerPort != nil {
		in, out := &in.ServerPort, &out.ServerPort
		*out = new(int)
		**out = **in
	}
	if in.AdminEnableServer != nil {
		in, out := &in.AdminEnableServer, &out.AdminEnableServer
		*out = new(bool)
		**out = **in
	}
	if in.AdminPort != nil {
		in, out := &in.AdminPort, &out.AdminPort
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperConfiguration.
func (in *ZookeeperConfiguration) DeepCopy() *ZookeeperConfiguration {
	if in == nil {
		return nil
	}
	out := new(ZookeeperConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperList) DeepCopyInto(out *ZookeeperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Zookeeper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperList.
func (in *ZookeeperList) DeepCopy() *ZookeeperList {
	if in == nil {
		return nil
	}
	out := new(ZookeeperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ZookeeperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperSpec) DeepCopyInto(out *ZookeeperSpec) {
	*out = *in
	in.CommonConfiguration.DeepCopyInto(&out.CommonConfiguration)
	in.ServiceConfiguration.DeepCopyInto(&out.ServiceConfiguration)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperSpec.
func (in *ZookeeperSpec) DeepCopy() *ZookeeperSpec {
	if in == nil {
		return nil
	}
	out := new(ZookeeperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperStatus) DeepCopyInto(out *ZookeeperStatus) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Degraded != nil {
		in, out := &in.Degraded, &out.Degraded
		*out = new(bool)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Ports = in.Ports
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperStatus.
func (in *ZookeeperStatus) DeepCopy() *ZookeeperStatus {
	if in == nil {
		return nil
	}
	out := new(ZookeeperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperStatusPorts) DeepCopyInto(out *ZookeeperStatusPorts) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperStatusPorts.
func (in *ZookeeperStatusPorts) DeepCopy() *ZookeeperStatusPorts {
	if in == nil {
		return nil
	}
	out := new(ZookeeperStatusPorts)
	in.DeepCopyInto(out)
	return out
}
